# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=hash/fnv1a32
GOFILES=\
	fnv1a32.go\

include $(GOROOT)/src/Make.pkg
